/* TIP — home-page i18n. Order: [en,es,fr,zh,hi,ar,ru]. HTML allowed in values. */
(function(){
var ORDER=["en","es","fr","zh","hi","ar","ru"];
var D={
kicker:["The Imagination Project · est. 2025","The Imagination Project · fund. 2025","The Imagination Project · fondé en 2025","想象计划 · 创立于2025年","द इमेजिनेशन प्रोजेक्ट · स्थापना 2025","مشروع الخيال · تأسس 2025","The Imagination Project · осн. 2025"],
mission_s:["Depolarizing the technologically overreliant and underresourced communities across the world.","Despolarizamos a las comunidades tecnológicamente sobredependientes y con pocos recursos en todo el mundo.","Dépolariser les communautés technologiquement surdépendantes et sous-dotées à travers le monde.","为全球过度依赖技术与资源匮乏的社区消除两极分化。","दुनिया भर में तकनीक पर अत्यधिक निर्भर और संसाधनहीन समुदायों का ध्रुवीकरण समाप्त कर रहे हैं।","نزيل الاستقطاب عن المجتمعات المفرطة في الاعتماد على التقنية والمحرومة من الموارد حول العالم.","Мы устраняем поляризацию сообществ, чрезмерно зависимых от технологий и лишённых ресурсов, по всему миру."],
scroll:["Scroll","Desliza","Défiler","滚动","स्क्रॉल","مرِّر","Листайте"],
readin:["Read it in","Léelo en","Lisez-le en","切换语言","भाषा चुनें","اقرأها بـ","Читайте на"],
nav_about:["About","Nosotros","À propos","关于","परिचय","من نحن","О нас"],
nav_gi:["Get Involved","Participa","Participer","参与","जुड़ें","شارك","Участвовать"],
nav_soc:["Socials","Redes","Réseaux","社交","सोशल","تواصل","Соцсети"],
d_explore:["Explore","Explora","Explorer","探索","खोजें","استكشف","Разделы"],
d_prog:["Programs","Programas","Programmes","项目","कार्यक्रम","البرامج","Программы"],
d_imp:["Impact","Impacto","Impact","影响","प्रभाव","الأثر","Влияние"],
m_ink:['AI is rewriting the world in <em>one language</em>. We are a youth-led nonprofit driving <span class="gold">every person</span> to protect our education, and support those without the same resources.','La IA está reescribiendo el mundo en <em>un solo idioma</em>. Somos una organización juvenil sin fines de lucro que impulsa a <span class="gold">cada persona</span> a proteger nuestra educación y apoyar a quienes no tienen los mismos recursos.','L\'IA réécrit le monde dans <em>une seule langue</em>. Nous sommes une association dirigée par des jeunes qui pousse <span class="gold">chacun</span> à protéger notre éducation et à soutenir ceux qui n\'ont pas les mêmes ressources.','人工智能正在用<em>一种语言</em>改写世界。我们是一家青年主导的公益组织，推动<span class="gold">每个人</span>守护我们的教育，并支持资源匮乏的人们。','एआई दुनिया को <em>एक ही भाषा</em> में फिर से लिख रहा है। हम एक युवा-नेतृत्व वाली संस्था हैं जो <span class="gold">हर व्यक्ति</span> को शिक्षा की रक्षा करने और संसाधनों से वंचित लोगों का साथ देने के लिए प्रेरित करती है।','الذكاء الاصطناعي يعيد كتابة العالم <em>بلغة واحدة</em>. نحن منظمة غير ربحية يقودها الشباب تدفع <span class="gold">كل شخص</span> لحماية تعليمنا ودعم من لا يملكون الموارد ذاتها.','ИИ переписывает мир на <em>одном языке</em>. Мы — молодёжная некоммерческая организация, побуждающая <span class="gold">каждого</span> защищать наше образование и поддерживать тех, у кого нет таких же ресурсов.'],
m_what:["What we do","Qué hacemos","Ce que nous faisons","我们的工作","हम क्या करते हैं","ما نفعله","Что мы делаем"],
m_side:["The Imagination Project translates digital literacy education into the languages of underresourced communities — from elementary classrooms to developing countries — and builds the research, mentorship, and programs that give young people agency over digital safety.","The Imagination Project traduce la educación en alfabetización digital a los idiomas de comunidades con pocos recursos — desde aulas de primaria hasta países en desarrollo — y construye la investigación, la mentoría y los programas que dan a los jóvenes agencia sobre la seguridad digital.","The Imagination Project traduit l'éducation à la littératie numérique dans les langues des communautés sous-dotées — des classes de primaire aux pays en développement — et bâtit la recherche, le mentorat et les programmes qui donnent aux jeunes une réelle prise sur la sécurité numérique.","想象计划将数字素养教育翻译成资源匮乏社区的语言——从小学课堂到发展中国家——并建设让年轻人掌握数字安全主动权的研究、导师制与项目。","द इमेजिनेशन प्रोजेक्ट डिजिटल साक्षरता शिक्षा का संसाधनहीन समुदायों की भाषाओं में अनुवाद करता है — प्राथमिक कक्षाओं से लेकर विकासशील देशों तक — और ऐसे शोध, मेंटरशिप और कार्यक्रम बनाता है जो युवाओं को डिजिटल सुरक्षा पर अधिकार देते हैं।","يترجم مشروع الخيال تعليم المهارات الرقمية إلى لغات المجتمعات المحرومة — من فصول الابتدائية إلى الدول النامية — ويبني الأبحاث والإرشاد والبرامج التي تمنح الشباب القدرة على التحكم في سلامتهم الرقمية.","The Imagination Project переводит образование в области цифровой грамотности на языки сообществ с ограниченными ресурсами — от начальных классов до развивающихся стран — и создаёт исследования, наставничество и программы, дающие молодым людям контроль над цифровой безопасностью."],
m_btn:['Why TIP exists <span class="arr">→</span>','Por qué existe TIP <span class="arr">→</span>','Pourquoi TIP existe <span class="arr">→</span>','为什么有TIP <span class="arr">→</span>','TIP क्यों है <span class="arr">→</span>','لماذا وُجد TIP <span class="arr">→</span>','Зачем существует TIP <span class="arr">→</span>'],
w_eyebrow:["The work","El trabajo","Le travail","我们的行动","कार्य","العمل","Наша работа"],
w_h:['How does TIP <em>enable change?</em>','¿Cómo impulsa TIP <em>el cambio?</em>','Comment TIP <em>rend-il le changement possible&nbsp;?</em>','TIP 如何<em>推动改变？</em>','TIP कैसे <em>बदलाव लाता है?</em>','كيف يصنع TIP <em>التغيير؟</em>','Как TIP <em>создаёт перемены?</em>'],
r1_t:["Translate","Traducir","Traduire","翻译","अनुवाद","الترجمة","Перевод"],
r1_p:["Students translate AI education into as many languages as possible — earning service hours while closing the digital divide for kids and communities neglected by the AI boom.","Estudiantes traducen la educación en IA a tantos idiomas como sea posible — ganando horas de servicio mientras cierran la brecha digital para niños y comunidades olvidadas por el auge de la IA.","Des élèves traduisent l'éducation à l'IA dans le plus de langues possible — cumulant des heures de service tout en réduisant la fracture numérique pour les enfants et les communautés délaissées par l'essor de l'IA.","学生将人工智能教育翻译成尽可能多的语言——在获得服务时长的同时，为被AI浪潮忽视的孩子和社区弥合数字鸿沟。","छात्र एआई शिक्षा का अधिक से अधिक भाषाओं में अनुवाद करते हैं — सेवा घंटे अर्जित करते हुए उन बच्चों और समुदायों के लिए डिजिटल खाई पाटते हैं जिन्हें एआई क्रांति ने छोड़ दिया।","يترجم الطلاب تعليم الذكاء الاصطناعي إلى أكبر عدد ممكن من اللغات — فيكسبون ساعات خدمة بينما يسدّون الفجوة الرقمية للأطفال والمجتمعات التي أهملتها طفرة الذكاء الاصطناعي.","Студенты переводят образование в области ИИ на максимально возможное число языков — зарабатывая часы волонтёрства и сокращая цифровой разрыв для детей и сообществ, забытых бумом ИИ."],
r2_t:["The AI Index","El Índice de IA","L'Index IA","AI指数","एआई इंडेक्स","مؤشر الذكاء الاصطناعي","Индекс ИИ"],
r2_p:["Investigative research with data scientists, building a precise index that scores how colleges use and rely on AI — designed to address the issue of AI accountability across US campuses.","Investigación con científicos de datos para construir un índice preciso que mide cómo las universidades usan y dependen de la IA — diseñado para abordar la rendición de cuentas de la IA en los campus de EE. UU.","Une recherche d'investigation menée avec des data scientists pour bâtir un index précis mesurant l'usage et la dépendance des universités à l'IA — conçu pour traiter la responsabilité de l'IA sur les campus américains.","与数据科学家合作开展调查研究，打造精确衡量高校使用和依赖AI程度的指数——旨在解决全美校园的AI问责问题。","डेटा वैज्ञानिकों के साथ खोजी शोध — एक सटीक इंडेक्स जो मापता है कि कॉलेज एआई का कितना उपयोग करते हैं और उस पर कितने निर्भर हैं — अमेरिकी कैंपसों में एआई जवाबदेही के लिए।","بحث استقصائي مع علماء بيانات لبناء مؤشر دقيق يقيس مدى استخدام الجامعات للذكاء الاصطناعي واعتمادها عليه — مصمم لمعالجة مساءلة الذكاء الاصطناعي في الجامعات الأمريكية.","Исследовательская работа с учёными по данным: точный индекс того, как колледжи используют ИИ и зависят от него, — создан для решения вопроса подотчётности ИИ в кампусах США."],
r3_t:["The Education Hub","El Centro Educativo","Le Hub Éducatif","教育中心","एजुकेशन हब","مركز التعليم","Образовательный хаб"],
r3_p:["Speakers, podcasts, and career-path learning to support irreplaceable human skills: featuring mentorship, multi-cultural discussion, long-term projects, and advocacy.","Ponentes, pódcasts y aprendizaje por trayectorias profesionales para cultivar habilidades humanas insustituibles: mentoría, diálogo multicultural, proyectos a largo plazo y activismo.","Conférences, podcasts et parcours de carrière pour cultiver les compétences humaines irremplaçables : mentorat, dialogue multiculturel, projets au long cours et plaidoyer.","演讲、播客与职业路径学习，培养无可替代的人类技能：导师制、多元文化讨论、长期项目与倡导。","वक्ता, पॉडकास्ट और करियर-पथ शिक्षा — अपूरणीय मानवीय कौशल के लिए: मेंटरशिप, बहु-सांस्कृतिक संवाद, दीर्घकालिक परियोजनाएँ और एडवोकेसी।","متحدثون وبودكاست وتعلّم قائم على المسارات المهنية لدعم المهارات الإنسانية التي لا تُستبدل: الإرشاد والحوار متعدد الثقافات والمشاريع طويلة الأمد والمناصرة.","Спикеры, подкасты и обучение по карьерным трекам для развития незаменимых человеческих навыков: наставничество, мультикультурный диалог, долгосрочные проекты и адвокация."],
tag_act:["Active now","Activo","Actif","进行中","सक्रिय","نشط الآن","Идёт сейчас"],
tag_dev:["In development","En desarrollo","En développement","开发中","निर्माणाधीन","قيد التطوير","В разработке"],
tag_soon:["Coming soon","Muy pronto","Bientôt","即将推出","जल्द ही","قريباً","Скоро"],
s1:["Elementary students taught","Estudiantes de primaria formados","Élèves de primaire formés","名小学生受教","प्राथमिक छात्र पढ़ाए गए","تلميذاً ابتدائياً تعلّموا","учеников начальной школы"],
s2:["Women funded in Ahmedabad, India","Mujeres financiadas en Ahmedabad, India","Femmes soutenues à Ahmedabad, Inde","位印度艾哈迈达巴德妇女受助","अहमदाबाद, भारत में महिलाओं को सहायता","امرأة مدعومة في أحمد آباد، الهند","женщин получили поддержку в Ахмадабаде"],
s3:["Our language translation goal","Nuestra meta de idiomas","Notre objectif de langues","种语言的翻译目标","भाषाओं का हमारा लक्ष्य","لغة هي هدفنا في الترجمة","языков — наша цель перевода"],
s4:["Founded in Texas","Fundado en Texas","Fondé au Texas","创立于德克萨斯","टेक्सास में स्थापित","تأسس في تكساس","Основан в Техасе"],
f_eyebrow:["Flagship program","Programa insignia","Programme phare","旗舰项目","प्रमुख कार्यक्रम","برنامجنا الرائد","Флагманская программа"],
f_lead:["Written and delivered to more than five hundred elementary students across Texas in its first four months — Laika's curriculum to inspire interdisciplinary pursuits and service-oriented action.","Escrito y presentado a más de quinientos estudiantes de primaria en Texas en sus primeros cuatro meses — el currículo de Laika para inspirar vocaciones interdisciplinarias y acción de servicio.","Écrit et présenté à plus de cinq cents élèves de primaire au Texas en quatre mois — le programme de Laika pour inspirer des vocations interdisciplinaires et l'action au service des autres.","在最初四个月内为德州五百多名小学生编写并授课——Laika的课程旨在激发跨学科追求与服务行动。","पहले चार महीनों में टेक्सास के पाँच सौ से अधिक प्राथमिक छात्रों तक पहुँचा — अंतःविषय रुचियों और सेवा-भावना को प्रेरित करने वाला लाइका का पाठ्यक्रम।","كُتب وقُدِّم لأكثر من خمسمئة تلميذ ابتدائي في تكساس خلال أشهره الأربعة الأولى — منهج لايكا لإلهام المساعي متعددة التخصصات والعمل الخدمي.","Написана и проведена более чем для пятисот учеников начальных школ Техаса за первые четыре месяца — программа Лайки, вдохновляющая на междисциплинарные занятия и служение."],
f_b1:["The accompanying children's book funds literacy and hygiene programs for 800+ women served by Manav Sadhna in Ahmedabad, India.","El libro infantil que la acompaña financia programas de alfabetización e higiene para más de 800 mujeres atendidas por Manav Sadhna en Ahmedabad, India.","Le livre pour enfants qui l'accompagne finance des programmes d'alphabétisation et d'hygiène pour plus de 800 femmes accompagnées par Manav Sadhna à Ahmedabad, en Inde.","配套童书为印度艾哈迈达巴德Manav Sadhna服务的800多名妇女的识字与卫生项目提供资金。","साथ की बाल-पुस्तक अहमदाबाद, भारत में मानव साधना द्वारा सेवा प्राप्त 800+ महिलाओं के साक्षरता व स्वच्छता कार्यक्रमों को निधि देती है।","يموّل كتاب الأطفال المرافق برامج محو الأمية والنظافة لأكثر من 800 امرأة تخدمهن مؤسسة ماناف سادهنا في أحمد آباد بالهند.","Сопутствующая детская книга финансирует программы грамотности и гигиены для более чем 800 женщин, которым помогает Manav Sadhna в Ахмадабаде."],
f_b2:["<b>Bilingual edition</b> — with conjugation and vocabulary charts for budding French learners.","<b>Edición bilingüe</b> — con tablas de conjugación y vocabulario para quienes empiezan con el francés.","<b>Édition bilingue</b> — avec tableaux de conjugaison et de vocabulaire pour les apprentis francophones.","<b>双语版</b>——附动词变位与词汇表，适合法语初学者。","<b>द्विभाषी संस्करण</b> — फ्रेंच सीखने वालों के लिए क्रिया-रूप और शब्दावली चार्ट सहित।","<b>طبعة ثنائية اللغة</b> — مع جداول تصريف ومفردات لمتعلمي الفرنسية الناشئين.","<b>Двуязычное издание</b> — с таблицами спряжений и словарём для начинающих изучать французский."],
f_note:["Dear Future Leader: The Wondermaker — available on Amazon","Dear Future Leader: The Wondermaker — en Amazon","Dear Future Leader: The Wondermaker — sur Amazon","《Dear Future Leader: The Wondermaker》——亚马逊有售","Dear Future Leader: The Wondermaker — Amazon पर उपलब्ध","Dear Future Leader: The Wondermaker — متوفر على أمازون","Dear Future Leader: The Wondermaker — на Amazon"],
f_pb:['Paperback <span class="arr">→</span>','Tapa blanda <span class="arr">→</span>','Broché <span class="arr">→</span>','平装版 <span class="arr">→</span>','पेपरबैक <span class="arr">→</span>','غلاف ورقي <span class="arr">→</span>','Мягкая обложка <span class="arr">→</span>'],
f_hc:['Bilingual hardcover <span class="arr">→</span>','Tapa dura bilingüe <span class="arr">→</span>','Relié bilingue <span class="arr">→</span>','双语精装版 <span class="arr">→</span>','द्विभाषी हार्डकवर <span class="arr">→</span>','غلاف صلب ثنائي اللغة <span class="arr">→</span>','Твёрдый переплёт (двуязычный) <span class="arr">→</span>'],
q_eyebrow:["From our founder","De nuestra fundadora","De notre fondatrice","创始人寄语","हमारी संस्थापक से","من مؤسِّستنا","От основательницы"],
q_text:['"Depolarizing education allows us the foundation to imagine. <em>Imagination allows us to break free of existing patterns.</em>"','"Despolarizar la educación nos da la base para imaginar. <em>La imaginación nos permite liberarnos de los patrones existentes.</em>"','« Dépolariser l\'éducation nous donne la base pour imaginer. <em>L\'imagination nous permet de nous libérer des schémas existants.</em> »','"消除教育的两极分化，让我们拥有想象的根基。<em>想象让我们挣脱既有的模式。</em>"','"शिक्षा का ध्रुवीकरण मिटाना हमें कल्पना की नींव देता है। <em>कल्पना हमें बने-बनाए ढाँचों से मुक्त करती है।</em>"','"إزالة الاستقطاب عن التعليم تمنحنا أساساً للخيال. <em>والخيال يحررنا من الأنماط القائمة.</em>"','«Деполяризация образования даёт нам основу для воображения. <em>Воображение освобождает нас от привычных шаблонов.</em>»'],
q_role:["Founder · Yale University","Fundadora · Universidad de Yale","Fondatrice · Université Yale","创始人 · 耶鲁大学","संस्थापक · येल विश्वविद्यालय","المؤسِّسة · جامعة ييل","Основательница · Йельский университет"],
c_eyebrow:["Join us","Únete","Rejoignez-nous","加入我们","जुड़िए","انضم إلينا","Присоединяйтесь"],
c_h:['Imagine better, <em>with us.</em>','Imagina mejor, <em>con nosotros.</em>','Imaginez mieux, <em>avec nous.</em>','与我们一起，<em>想象更好。</em>','हमारे साथ, <em>बेहतर की कल्पना करें।</em>','تخيّل أفضل، <em>معنا.</em>','Представьте лучшее — <em>вместе с нами.</em>'],
c_p:["Join the TIP community to translate a lesson, start a chapter, lend your research, and so much more.","Únete a la comunidad TIP para traducir una lección, abrir un capítulo, aportar tu investigación y mucho más.","Rejoignez la communauté TIP pour traduire une leçon, lancer un chapitre, contribuer à la recherche et bien plus.","加入TIP社区：翻译课程、创办分会、贡献研究，还有更多。","TIP समुदाय से जुड़ें — पाठ का अनुवाद करें, चैप्टर शुरू करें, शोध में योगदान दें, और बहुत कुछ।","انضم إلى مجتمع TIP لترجمة درس أو تأسيس فرع أو دعم البحث وأكثر من ذلك بكثير.","Присоединяйтесь к сообществу TIP: переведите урок, откройте отделение, поддержите исследование — и не только."],
c_btn:['Get involved <span class="arr">→</span>','Participa <span class="arr">→</span>','Participer <span class="arr">→</span>','参与 <span class="arr">→</span>','जुड़ें <span class="arr">→</span>','شارك <span class="arr">→</span>','Участвовать <span class="arr">→</span>'],
ft_stay:["Stay close","Mantente cerca","Restez proches","保持联系","जुड़े रहें","ابقَ قريباً","Будьте рядом"],
ft_stayp:["Essays, program updates, and more — on our Substack.","Ensayos, novedades de los programas y más — en nuestro Substack.","Essais, actualités des programmes et plus — sur notre Substack.","随笔、项目动态及更多——尽在我们的Substack。","निबंध, कार्यक्रम अपडेट और बहुत कुछ — हमारे Substack पर।","مقالات وتحديثات البرامج والمزيد — على Substack.","Эссе, новости программ и многое другое — в нашем Substack."],
ft_sub:['Subscribe <span class="arr">→</span>','Suscríbete <span class="arr">→</span>','S\'abonner <span class="arr">→</span>','订阅 <span class="arr">→</span>','सब्सक्राइब करें <span class="arr">→</span>','اشترك <span class="arr">→</span>','Подписаться <span class="arr">→</span>'],
ft_tag:["Imagine better · write our future","Imagina mejor · escribe nuestro futuro","Imaginez mieux · écrivez notre avenir","想象更好 · 书写我们的未来","बेहतर की कल्पना करें · हमारा भविष्य लिखें","تخيّل أفضل · اكتب مستقبلنا","Представь лучшее · напиши наше будущее"],
map_eyebrow:["Global digital literacy","Alfabetización digital global","Littératie numérique mondiale","全球数字素养","वैश्विक डिजिटल साक्षरता","محو الأمية الرقمية عالمياً","Глобальная цифровая грамотность"],
map_h:['One world, <em>many futures</em>','Un mundo, <em>muchos futuros</em>','Un monde, <em>mille avenirs</em>','同一个世界，<em>多样的未来</em>','एक दुनिया, <em>अनेक भविष्य</em>','عالم واحد، <em>مستقبلات كثيرة</em>','Один мир — <em>много будущих</em>'],
tab_learn:["Learn the world","Explora el mundo","Explorer le monde","认识世界","दुनिया जानें","تعرّف على العالم","Изучайте мир"],
tab_guess:["Do you know your countries?","¿Conoces tus países?","Connaissez-vous vos pays ?","你认识这些国家吗？","क्या आप देश पहचानते हैं?","هل تعرف بلدان العالم؟","Знаете ли вы страны?"],
map_hint:["Hover any country for its digital-literacy numbers.","Pasa el cursor por un país para ver sus cifras.","Survolez un pays pour voir ses chiffres.","悬停任意国家查看数字素养数据。","किसी देश पर होवर करें और आँकड़े देखें।","مرر المؤشر فوق أي بلد لرؤية أرقامه.","Наведите на страну, чтобы увидеть её показатели."],
map_int:["Internet access","Acceso a internet","Accès à Internet","互联网普及率","इंटरनेट पहुँच","الوصول إلى الإنترنت","Доступ к интернету"],
map_lit:["Adult literacy","Alfabetización adulta","Alphabétisation des adultes","成人识字率","वयस्क साक्षरता","معرفة القراءة لدى البالغين","Грамотность взрослых"],
map_nodata:["No data","Sin datos","Pas de données","暂无数据","डेटा उपलब्ध नहीं","لا بيانات","Нет данных"],
g_region:["Region","Región","Région","区域","क्षेत्र","المنطقة","Регион"],
g_world:["World","Mundo","Monde","全世界","विश्व","العالم","Весь мир"],
g_af:["Africa","África","Afrique","非洲","अफ़्रीका","أفريقيا","Африка"],
g_as:["Asia","Asia","Asie","亚洲","एशिया","آسيا","Азия"],
g_eu:["Europe","Europa","Europe","欧洲","यूरोप","أوروبا","Европа"],
g_am:["Americas","América","Amériques","美洲","अमेरिका","الأمريكتان","Америка"],
g_oc:["Oceania","Oceanía","Océanie","大洋洲","ओशिनिया","أوقيانوسيا","Океания"],
g_mode:["Answer style","Modo de respuesta","Mode de réponse","作答方式","उत्तर शैली","طريقة الإجابة","Формат ответа"],
g_type:["Type it","Escríbelo","Au clavier","键盘输入","टाइप करें","اكتبها","Ввод с клавиатуры"],
g_mc:["Multiple choice","Opción múltiple","Choix multiple","选择题","विकल्प चुनें","اختيار من متعدد","Варианты"],
g_free:["Name them all","Nómbralos todos","Nommez-les tous","全部说出","सभी बताएं","سمِّ الجميع","Назови все"],
g_free_prompt:["Type every country you can — 10 minutes","Escribe todos los países que puedas — 10 minutos","Tapez tous les pays possibles — 10 minutes","在10分钟内输入尽可能多的国家","10 मिनट में जितने देश लिख सकें लिखें","اكتب كل البلدان التي تستطيع — 10 دقائق","Назовите как можно больше стран — 10 минут"],
g_stop:["Give up","Rendirse","Abandonner","放弃","हार मानें","استسلم","Сдаться"],
g_start:["Start","Empezar","Commencer","开始","शुरू करें","ابدأ","Начать"],
g_score:["Score","Puntos","Score","得分","स्कोर","النقاط","Счёт"],
g_skip:["Skip","Saltar","Passer","跳过","छोड़ें","تخطَّ","Пропустить"],
g_guess:["Guess","Adivinar","Valider","提交","जवाब दें","خمّن","Ответить"],
g_ph:["Type a country…","Escribe un país…","Tapez un pays…","输入国家名（英文）…","देश लिखें (अंग्रेज़ी)…","اكتب اسم البلد (بالإنجليزية)…","Введите страну (англ.)…"],
g_prompt:["Name the highlighted country","Nombra el país resaltado","Nommez le pays en surbrillance","说出高亮国家的名字","हाइलाइट किए गए देश का नाम बताएं","سمِّ البلد المميز","Назовите выделенную страну"],
g_end:["Time's up!","¡Se acabó el tiempo!","Temps écoulé !","时间到！","समय समाप्त!","انتهى الوقت!","Время вышло!"],
g_was:["It was","Era","C'était","答案是","सही उत्तर","الإجابة الصحيحة","Правильный ответ"],
g_again:["Play again","Jugar de nuevo","Rejouer","再玩一次","फिर खेलें","العب مجدداً","Играть снова"],
g_fs:["Fullscreen","Pantalla completa","Plein écran","全屏","फ़ुल स्क्रीन","ملء الشاشة","Во весь экран"],
map_close:["You're not expected to know every country — but that sense of global literacy is something we hope to build, so our imaginations of the future don't confine us to a single nationality, but allow us to embrace them all.","Nadie espera que conozcas todos los países — pero esa alfabetización global es la que queremos construir, para que nuestra imaginación del futuro no nos limite a una sola nacionalidad, sino que nos permita abrazarlas todas.","Personne n'attend de vous que vous connaissiez chaque pays — mais c'est cette littératie mondiale que nous voulons bâtir, pour que nos imaginaires du futur ne nous enferment pas dans une seule nationalité, mais nous permettent de les embrasser toutes.","没有人要求你认识每一个国家——但这份全球素养正是我们希望培养的：让我们对未来的想象不局限于某一个国籍，而是拥抱所有国籍。","हर देश जानने की अपेक्षा नहीं है — पर यही वैश्विक साक्षरता हम बनाना चाहते हैं, ताकि भविष्य की हमारी कल्पना हमें किसी एक राष्ट्रीयता में न बाँधे, बल्कि सबको अपनाने दे।","لا يُتوقع منك معرفة كل بلد — لكن هذا الوعي العالمي هو ما نأمل بناءه، حتى لا يحصرنا خيالنا للمستقبل في جنسية واحدة، بل يتيح لنا احتضانها جميعاً.","Никто не ждёт, что вы знаете каждую страну, — но именно такую глобальную грамотность мы хотим развивать, чтобы наши представления о будущем не ограничивали нас одной национальностью, а позволяли принять их все."]
};
var cur=localStorage.getItem('tip_lang')||'en';
if(ORDER.indexOf(cur)<0)cur='en';
function t(key){var e=D[key];if(!e)return '';var i=ORDER.indexOf(cur);return e[i]||e[0];}
function apply(lang){
  if(ORDER.indexOf(lang)<0)lang='en';
  cur=lang;window.TIP_LANG=lang;
  try{localStorage.setItem('tip_lang',lang);}catch(e){}
  document.documentElement.lang=lang==='zh'?'zh-Hans':lang;
  document.documentElement.dir=lang==='ar'?'rtl':'ltr';
  document.querySelectorAll('[data-t]').forEach(function(el){
    var v=t(el.getAttribute('data-t'));if(v)el.innerHTML=v;
  });
  document.querySelectorAll('[data-t-ph]').forEach(function(el){
    var v=t(el.getAttribute('data-t-ph'));if(v)el.setAttribute('placeholder',v);
  });
  if(window.__tipInk)window.__tipInk();
  if(window.TIPAtlas&&window.TIPAtlas.onLang)window.TIPAtlas.onLang();
}
window.TIP_I18N={t:t,apply:apply,current:function(){return cur;},langs:ORDER};
window.TIP_LANG=cur;
})();
